{% set PKG_NAME = 'mr-box-peripheral-board' %}
{% set PLATFORMIO_ENVS = 'default'.split(' ') %}
{% set LIB_NAME = 'MrBoxPeripheralBoard' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: {{ PKG_NAME }}
  version: 1.0.0

build:
  noarch: python
  entry_points:
    - mr-box-peripheral-board-upload = mr_box_peripheral_board.bin.upload:upload
  script:
    # Generate Arduino code
    - python file_handler.py
    -
    # Install source directory as Python package.
    - python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python {{ python }}
    - protobuf 3.20.*
    - six
    - base-node-rpc
    - clang=5.0.0
    - python-clang=5.0.0
    - clang-helpers=0.9.1
    - m2w64-toolchain
    -
outputs:
  - name: {{ PKG_NAME }}
    noarch: python
    files:
      - Lib/site-packages/{{ MODULE_NAME }}
    requirements:
      run:
        - python {{ python }}
        - protobuf 3.20.*
        - six
        - base-node-rpc
        - m2w64-toolchain
    test:
      imports:
        - mr_box_peripheral_board
        - mr_box_peripheral_board.proxy


about:
  home: https://github.com/wheeler-microfluidics/mr-box-peripheral-board.py
  license: MIT
