{% set PKG_NAME = 'mr-box-peripheral-board' %}
{% set PLATFORMIO_ENVS = 'default'.split(' ') %}
{% set LIB_NAME = 'MrBoxPeripheralBoard' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: {{ PKG_NAME }}
  version: 1.0.0

build:
  noarch: python
  script:
    # Ensure Python script is executed in a clean environment
    - python generate_python_files.py
    # Install the Python package using pip for better compatibility
    - pip install . --no-deps --ignore-installed --no-cache-dir

requirements:
  build:
    - python {{ python }}
    - protobuf 3.20.3
    - protoc 3.1.0
    - clang 5.0.0
    - python-clang 5.0.0
    - clang-helpers 0.9.1
    - six
    - base-node-rpc
    - m2w64-toolchain

  run:
    - python {{ python }}
    - protobuf 3.20.3
    - protoc 3.1.0
    - six
    - base-node-rpc
    - ntfsutils # [win]
    - m2w64-toolchain  # this should not be here, but in nadamq. That update needs to be done at some point. Workaround it by having this here. If in an environemnt with dropbot.py already installed. We cna just install with --no-deps option.

test:
  imports:
    - {{ MODULE_NAME }}
    - {{ MODULE_NAME }}.proxy

about:
  home: https://github.com/wheeler-microfluidics/mr-box-peripheral-board.py
  license: MIT
